### ISSUE TITLE
打包出现错误

### ISSUE THREAD

**Issue by JiangJuHong** [fluttify-project/amap_location_fluttify#32]
**插件版本**
我的版本是 0.7.0+5a112a2，我在执行Android打包时遇到了下面这些错误信息:
```
FAILURE: Build failed with an exception.

* Where:
Build file '/Users/jiangjuhong/.pub-cache/hosted/pub.flutter-io.cn/amap_core_fluttify-0.4.0+e26c0fa/android/build.gradle' line: 47

* What went wrong:
A problem occurred evaluating root project 'amap_core_fluttify'.
> Cannot convert a null value to an object of type Dependency.
  The following types/formats are supported:
    - Instances of Dependency.
    - String or CharSequence values, for example 'org.gradle:gradle-core:1.0'.
    - Maps, for example [group: 'org.gradle', name: 'gradle-core', version: '1.0'].
    - FileCollections, for example files('some.jar', 'someOther.jar').
    - Projects, for example project(':some:project:path').
    - ClassPathNotation, for example gradleApi().

  Comprehensive documentation on dependency notations is available in DSL reference for DependencyHandler type.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 614ms


The plugin amap_core_fluttify could not be built due to the issue above.

```

**Comment by xioxin** [comment]
同样的问题

**Comment by azhanglongfei** [comment]
同样的问题

**Comment by azhanglongfei** [comment]
android打包同样的问题

**Comment by hzp1993** [comment]
能问下有解决方案吗？我现在也遇到这个问题

**Comment by xioxin** [comment]
可能和某个包冲突，https://github.com/fluttify-project/amap_map_fluttify/issues/119#issuecomment-569219846

发自我的iPhone

**Comment by shichunlei** [comment]
0.8.3+4d92ce0     同样的问题。

FAILURE: Build failed with an exception.

* Where:
Build file '/Users/14cells/.pub-cache/hosted/pub.flutter-io.cn/amap_core_fluttify-0.5.2+68b910c/android/build.gradle' line: 48

* What went wrong:
A problem occurred evaluating root project 'amap_core_fluttify'.
> Cannot convert a null value to an object of type Dependency.
  The following types/formats are supported:
    - Instances of Dependency.
    - String or CharSequence values, for example 'org.gradle:gradle-core:1.0'.
    - Maps, for example [group: 'org.gradle', name: 'gradle-core', version: '1.0'].
    - FileCollections, for example files('some.jar', 'someOther.jar').
    - Projects, for example project(':some:project:path').
    - ClassPathNotation, for example gradleApi().

  Comprehensive documentation on dependency notations is available in DSL reference for DependencyHandler type.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 11s


The plugin amap_core_fluttify could not be built due to the issue above.

**Comment by shhrain** [comment]
请问这个问题解决了吗？

**Comment by bigtotorouk** [comment]
0.14还有这个问题

**Comment by 100cm** [comment]
2022年了 这问题还没解决吗
